{% set name = "pcr" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - pybind11 >=2.10
  host:
    - python
    - numpy
    - gdal
    - proj
  run:
    - python
    - numpy
    - gdal
    - proj

test:
  imports:
    - pcr
  commands:
    - pytest tests/python

about:
  home: https://github.com/pcr-dev/pcr
  license: MIT
  license_file: LICENSE
  summary: High-performance point cloud rasterization
  description: |
    PCR provides GPU-accelerated rasterization of massive point cloud
    datasets with CPU, GPU, and hybrid execution modes.
